### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by szwork2013** [ankeetmaini/react-infinite-scroll-component#30] opened 2017-09-12 17:04 UTC
get the error:
 Uncaught TypeError: Cannot read property 'style' of null,
It is this line from the source code of index.js:
  _this._infScroll.style.overflow = 'auto';

**Comment by LanceMango** [comment] 2017-11-03 14:19
I get the same error: In my case, I have a list of items and when I click on one item a "detailview" is loaded in the same wrapper. I think the problem is, that infinite-scroll looses context or has no context at all, so the _this is null and throws an error. Any idea?

**Comment by devlin-playlogix** [comment] 2017-11-17 11:37
+1 Also get this error on navigation. Is there anything special I should be doing in unmounting?

**Comment by jacqueswho** [comment] 2017-11-17 12:08
it has to do with the refresh functionality. if you leave out the refresh option. its no longer a problem. for now just leave out pullDownToRefresh prop

**Comment by ankeetmaini** [comment] 2017-11-17 19:09
Sorry guys for not getting to this. I'll investigate it this weekend, if you can share a reproducible example, it would be great!

**Comment by jacqueswho** [comment] 2017-11-20 07:59
It happens when you leave the page with this component.

**Comment by devlin-playlogix** [comment] 2017-11-20 08:16
hi @ankeetmaini 

Our implementation has:
```
<InfiniteScroll
      pullDownToRefresh
      pullDownToRefreshContent={<h3 style={{ textAlign: 'center' }}>&#8595; Pull down to refresh</h3>}
      releaseToRefreshContent={<h3 style={{ textAlign: 'center' }}>&#8593; Release to refresh</h3>}
      refreshFunction={refreshSearch}
      next={requestNextPage}
      hasMore={!pageSettings.isLastPage}
      loader={<h1>Loading...</h1>}
    >
```
This is inside a component fed all its properties and actions from its container.
The content is a map of tiles:
```
<Tile y={y} key={id} x={x} />);
```
These have click handlers on them that fire a navigate action.

```
<Link
                  to={`/url/${id}`}
                  className="btn btn--primary search-result-tile__book-btn"
                >{txt}</Link>
```

(This next bit is an assumption) 
Is it related to the click handler firing a drag action and navigate action at the same time, and then causing some actions to fire, while the component is un-mounting?

Thanks for any feedback.

**Comment by ankeetmaini** [comment] 2018-04-28 21:13
Hoping you got around the issue. Closing this as it's open for a long time now. Please reopen if you still face any issues.

**Closed by ankeetmaini** 2018-04-28 21:13 UTC

**Comment by ayushnawani** [comment] 2018-09-24 12:30
Did anyone get a solution for this issue? I am facing this same error on pulltorefresh.

**Comment by J4spr** [comment] 2018-12-25 16:13
I face the same error.. anything new?
